dbt_learning:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: project-ca830276-317b-4687-b78
      dataset: dbt_learning
      keyfile: ./keys/BIGQUERY.json
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
